services:

  service-a-container:
    build:
      context: ./service-a/
      dockerfile: Dockerfile
    container_name: svc-a-cont
    networks:
      - my-network
    ports:
      - "8081:8080"
    depends_on:
      - service-b-container
      - service-c-container

  service-b-container:
    build:
      context: ./service-b/
      dockerfile: Dockerfile
    container_name: svc-b-cont
    networks:
      - my-network
    ports:
      - "8082:8080"

  service-c-container:
    build:
      context: ./service-c/
      dockerfile: Dockerfile
    container_name: svc-c-cont
    networks:
      - my-network
    ports:
      - "8083:8080"

networks:
  my-network:
    driver: bridge
